[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "latin-macronizer"
version = "0.1.0"
description = "Mark long vowels in Latin text"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=2.20.0",
    "la-core-web-lg @ https://huggingface.co/latincy/la_core_web_lg/resolve/main/la_core_web_lg-3.9.6-py3-none-any.whl",
    "pydantic>=2.13.4",
    "spacy>=3.8.16",
]

[tool.uv.sources]
la-core-web-lg = { url = "https://huggingface.co/latincy/la_core_web_lg/resolve/main/la_core_web_lg-3.9.6-py3-none-any.whl" }